name: Docker Hello World

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t hello-world .

    - name: Run Docker container
      run: docker run hello-world
